name = "backend"
compatibility_date = "2025-03-3"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=your-api-key"
JWT_SECRET = "your-jwt-secret"

[env.dev]
DATABASE_URL = "postgresql://neondb_owner:npg_P6qHZxWlbj2G@ep-raspy-scene-a5d783uj-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
JWT_SECRET = "my-jwt-secret"
